// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdifptnbzgffavsihpgm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkaWZwdG5iemdmZmF2c2locGdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwODIwNzAsImV4cCI6MjA2MTY1ODA3MH0.T3Gnnjm4siXb855-2KGxh0otVkyEbQGSGRrmCj0q1o0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);